import React from "react";
import { PropertyDefaultWrapper } from "../../../../components/PropertyDefaultWrapper";
import "./style.css";

export const View = () => {
  return (
    <div className="view">
      <div className="vertical-border">
        <div className="background-2">
          <div className="text-wrapper-58">서울</div>
        </div>
      </div>

      <div className="vertical-border-2">
        <div className="frame-35">
          <PropertyDefaultWrapper
            buttontext="강남구"
            className="background-instance"
            property1="selected"
          />
          <PropertyDefaultWrapper
            buttontext="강동구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="강북구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="강서구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="관악구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="광진구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="구로구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="금천구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="노원구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="도봉구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="동대문구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="동작구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="마포구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="서대문구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="서초구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="성동구"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="성북구"
            className="design-component-instance-node"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="송파구"
            className="design-component-instance-node"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="양천구"
            className="design-component-instance-node"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="영등포구"
            className="design-component-instance-node"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="용산구"
            className="design-component-instance-node"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="은평구"
            className="design-component-instance-node"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="종로구"
            className="design-component-instance-node"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="중구"
            className="design-component-instance-node"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="중랑구"
            className="design-component-instance-node"
            property1="default"
          />
        </div>
      </div>

      <div className="vertical-border-2">
        <div className="frame-36">
          <PropertyDefaultWrapper
            buttontext="개포동"
            className="background-instance"
            property1="selected"
          />
          <PropertyDefaultWrapper
            buttontext="논현동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="대치동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="도곡동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="삼성동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="세곡동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="수서동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="신사동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="압구정동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="역삼동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="율현동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="일원동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="자곡동"
            className="background-instance"
            property1="default"
          />
          <PropertyDefaultWrapper
            buttontext="청담동"
            className="background-instance"
            property1="default"
          />
        </div>
      </div>
    </div>
  );
};
